/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fee_report;

import java.awt.Color;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
//import java.util.DateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author ANIK ADRISH MAJHI
 */
public class Print_Page extends javax.swing.JFrame {

    Connection con;
    /**
     * Creates new form Add_Fees
     */
    public Print_Page() {
        initComponents();
        getRecords();
    }
    
    public void getRecords(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_management","root","");
           PreparedStatement st = con.prepareStatement("select * from fees_details order by reciept_no desc limit 1");
           ResultSet rs = st.executeQuery();
           rs.next();
           txt_RecieptNo.setText(rs.getString("reciept_No"));
           txt_PaymentMode.setText(rs.getString("payment_mode"));
           
           String paymentMode = rs.getString("payment_mode");
           if(paymentMode.equalsIgnoreCase("Cash")){
               lbl_Cheque.setText("Cheque No :");
               txt_Cheque.setText("-");
               txt_BankName.setText("-");
           }
           
           if(paymentMode.equalsIgnoreCase("Cheque")){
               lbl_Cheque.setText("Cheque No");
               txt_Cheque.setText(rs.getString("cheque_no"));
               txt_BankName.setText(rs.getString("bank_name"));
           }
           
           if(paymentMode.equalsIgnoreCase("DD")){
               lbl_Cheque.setText("DD No");
               txt_Cheque.setText(rs.getString("dd_no"));
               txt_BankName.setText(rs.getString("bank_name"));
           }
           
           if(paymentMode.equalsIgnoreCase("Card")){
               lbl_Cheque.setText("Cheque No");
               txt_Cheque.setText("-");
               txt_BankName.setText(rs.getString("bank_name"));
           }
           
           txt_ReceivedForm.setText(rs.getString("student_name"));
           txt_date.setText(rs.getString("date"));
           txt_gstin.setText(rs.getString("gstin"));
           txt_Year1.setText(rs.getString("year1"));
           txt_Year2.setText(rs.getString("year2"));
           txt_Amount.setText(rs.getString("amount"));
           txt_cgst.setText(rs.getString("cgst"));
           txt_sgst.setText(rs.getString("sgst"));
           txt_Total.setText(rs.getString("total_amount"));
           txt_TotalInWord.setText(rs.getString("total_in_words"));
           txt_Remark.setText((rs.getString("remark")));
           txt_StreamName.setText(rs.getString("course_name"));
           
           
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_Logout = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_Home = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_Search = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btn_EditCourse = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btn_CourseList = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btn_ViewAllRecord = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btn_Back = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btn_Edit = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        btn_Logout2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        txt_RecieptNo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_PaymentMode = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Cheque = new javax.swing.JLabel();
        txt_BankName = new javax.swing.JLabel();
        txt_ReceivedForm = new javax.swing.JLabel();
        lbl_Cheque = new javax.swing.JLabel();
        lbl_BankName = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_Year1 = new javax.swing.JLabel();
        txt_Year2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        txt_StreamName = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        txt = new javax.swing.JLabel();
        txt_s = new javax.swing.JLabel();
        txt_Total = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_gstin = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_Amount = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txt_TotalInWord = new javax.swing.JLabel();
        txt_Remark = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), java.awt.Color.white, null, null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Logout.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        btn_Logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_report/image/my icons/logout.png"))); // NOI18N
        btn_Logout.setText("  Logout");
        btn_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseExited(evt);
            }
        });
        jPanel3.add(btn_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 260, 70));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Home.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        btn_Home.setForeground(new java.awt.Color(255, 255, 255));
        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_report/image/my icons/home.png"))); // NOI18N
        btn_Home.setText("  Home");
        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HomeMouseExited(evt);
            }
        });
        jPanel4.add(btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 260, 70));

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Search.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        btn_Search.setForeground(new java.awt.Color(255, 255, 255));
        btn_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_report/image/my icons/search2.png"))); // NOI18N
        btn_Search.setText("  Search Record");
        btn_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SearchMouseExited(evt);
            }
        });
        jPanel5.add(btn_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 60));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 260, 70));

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), java.awt.Color.white, null, null));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_EditCourse.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        btn_EditCourse.setForeground(new java.awt.Color(255, 255, 255));
        btn_EditCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_report/image/my icons/edit2.png"))); // NOI18N
        btn_EditCourse.setText("  Edit Courses");
        btn_EditCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EditCourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EditCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EditCourseMouseExited(evt);
            }
        });
        jPanel6.add(btn_EditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 260, 70));

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), java.awt.Color.white, null, null));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_CourseList.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        btn_CourseList.setForeground(new java.awt.Color(255, 255, 255));
        btn_CourseList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_report/image/my icons/list.png"))); // NOI18N
        btn_CourseList.setText("  Course List");
        btn_CourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CourseListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CourseListMouseExited(evt);
            }
        });
        jPanel7.add(btn_CourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 260, 70));

        jPanel8.setBackground(new java.awt.Color(0, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), java.awt.Color.white, null, null));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ViewAllRecord.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        btn_ViewAllRecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_ViewAllRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_report/image/my icons/view all record.png"))); // NOI18N
        btn_ViewAllRecord.setText("  View All Record");
        btn_ViewAllRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ViewAllRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ViewAllRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ViewAllRecordMouseExited(evt);
            }
        });
        jPanel8.add(btn_ViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 70));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 260, 70));

        jPanel9.setBackground(new java.awt.Color(0, 51, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), java.awt.Color.white, null, null));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Back.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        btn_Back.setForeground(new java.awt.Color(255, 255, 255));
        btn_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_report/image/my icons/left-arrow.png"))); // NOI18N
        btn_Back.setText("  Back");
        btn_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_BackMouseExited(evt);
            }
        });
        jPanel9.add(btn_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 260, 70));

        jPanel11.setBackground(new java.awt.Color(0, 51, 51));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), java.awt.Color.white, null, null));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Edit.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        btn_Edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_report/image/my icons/edit2.png"))); // NOI18N
        btn_Edit.setText("  Edit");
        btn_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EditMouseExited(evt);
            }
        });
        jPanel11.add(btn_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, -1));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 720, 260, 70));

        jPanel12.setBackground(new java.awt.Color(0, 51, 51));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), java.awt.Color.white, null, null));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Logout2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        btn_Logout2.setForeground(new java.awt.Color(255, 255, 255));
        btn_Logout2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_report/image/my icons/printer-.png"))); // NOI18N
        btn_Logout2.setText("  Print");
        btn_Logout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Logout2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Logout2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Logout2MouseExited(evt);
            }
        });
        jPanel12.add(btn_Logout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, -1));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 260, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 800));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        jLabel10.setText("Techno International New Town");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 540, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 25)); // NOI18N
        jLabel12.setText("B.Tech & B.Tech(Lat.)");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        jLabel11.setText("Newtown, Kolkata - 700156 ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 240, -1));

        jPanel10.setBackground(new java.awt.Color(0, 51, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1100, 5));

        txt_RecieptNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_RecieptNo.setForeground(new java.awt.Color(0, 51, 51));
        txt_RecieptNo.setText("Receipt No ");
        jPanel2.add(txt_RecieptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Reciept No :     TINT-");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txt_PaymentMode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_PaymentMode.setForeground(new java.awt.Color(0, 51, 51));
        txt_PaymentMode.setText("Mode of payment :");
        jPanel2.add(txt_PaymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Mode of payment :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txt_Cheque.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Cheque.setForeground(new java.awt.Color(0, 51, 51));
        txt_Cheque.setText("Cheque No :");
        jPanel2.add(txt_Cheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        txt_BankName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_BankName.setForeground(new java.awt.Color(0, 51, 51));
        txt_BankName.setText("Bank Name :");
        jPanel2.add(txt_BankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        txt_ReceivedForm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_ReceivedForm.setForeground(new java.awt.Color(0, 51, 51));
        txt_ReceivedForm.setText("Recieved From :");
        jPanel2.add(txt_ReceivedForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, 30));

        lbl_Cheque.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Cheque.setForeground(new java.awt.Color(0, 51, 51));
        lbl_Cheque.setText("Cheque No :");
        jPanel2.add(lbl_Cheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lbl_BankName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_BankName.setForeground(new java.awt.Color(0, 51, 51));
        lbl_BankName.setText("Bank Name :");
        jPanel2.add(lbl_BankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setText("   -");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("the following payment in the college office for the year :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 51));
        jLabel15.setText("Recieved From :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 30));

        txt_Year1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Year1.setForeground(new java.awt.Color(0, 51, 51));
        txt_Year1.setText("2000");
        jPanel2.add(txt_Year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, 30));

        txt_Year2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Year2.setForeground(new java.awt.Color(0, 51, 51));
        txt_Year2.setText("2000");
        jPanel2.add(txt_Year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 51, 51));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 1000, 20));

        jLabel19.setBackground(new java.awt.Color(0, 51, 51));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 51));
        jLabel19.setText("Serial No. :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        txt_StreamName.setBackground(new java.awt.Color(0, 51, 51));
        txt_StreamName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_StreamName.setForeground(new java.awt.Color(0, 51, 51));
        txt_StreamName.setText("Head");
        jPanel2.add(txt_StreamName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 100, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(0, 51, 51));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 640, 260, 20));

        jLabel18.setBackground(new java.awt.Color(0, 51, 51));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 51));
        jLabel18.setText("Amount (RS) ");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, -1, -1));

        txt.setBackground(new java.awt.Color(0, 51, 51));
        txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt.setForeground(new java.awt.Color(0, 51, 51));
        txt.setText("CGST 9%");
        jPanel2.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        txt_s.setBackground(new java.awt.Color(0, 51, 51));
        txt_s.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_s.setForeground(new java.awt.Color(0, 51, 51));
        txt_s.setText("SGST 9%");
        jPanel2.add(txt_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, -1));

        txt_Total.setBackground(new java.awt.Color(0, 51, 51));
        txt_Total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Total.setForeground(new java.awt.Color(0, 51, 51));
        txt_Total.setText("Head");
        jPanel2.add(txt_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("GSTIN :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Date :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, -1, -1));

        txt_gstin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_gstin.setForeground(new java.awt.Color(0, 51, 51));
        txt_gstin.setText("GSTIN :");
        jPanel2.add(txt_gstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, -1, -1));

        txt_date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_date.setForeground(new java.awt.Color(0, 51, 51));
        txt_date.setText("Date :");
        jPanel2.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, -1, -1));

        jLabel20.setBackground(new java.awt.Color(0, 51, 51));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 51));
        jLabel20.setText("Head");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        txt_Amount.setBackground(new java.awt.Color(0, 51, 51));
        txt_Amount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Amount.setForeground(new java.awt.Color(0, 51, 51));
        txt_Amount.setText("Head");
        jPanel2.add(txt_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, -1, -1));

        txt_cgst.setBackground(new java.awt.Color(0, 51, 51));
        txt_cgst.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_cgst.setForeground(new java.awt.Color(0, 51, 51));
        txt_cgst.setText("Head");
        jPanel2.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, -1, -1));

        txt_sgst.setBackground(new java.awt.Color(0, 51, 51));
        txt_sgst.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_sgst.setForeground(new java.awt.Color(0, 51, 51));
        txt_sgst.setText("Head");
        jPanel2.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator4.setForeground(new java.awt.Color(0, 51, 51));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 1000, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 51));
        jLabel17.setText("Total In Words :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 51));
        jLabel16.setText("Remark :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("Receiver Signature");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 640, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator5.setForeground(new java.awt.Color(0, 51, 51));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 460, 20));

        txt_TotalInWord.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_TotalInWord.setForeground(new java.awt.Color(0, 51, 51));
        txt_TotalInWord.setText("Total In Words :");
        jPanel2.add(txt_TotalInWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, -1, -1));

        txt_Remark.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Remark.setForeground(new java.awt.Color(0, 51, 51));
        txt_Remark.setText("Remark :");
        jPanel2.add(txt_Remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("1");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 1100, 700));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Print Reciept");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 370, 20));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 35)); // NOI18N
        jLabel2.setText("  X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 0, 60, -1));

        setSize(new java.awt.Dimension(1500, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseEntered
        Color clr = new Color(0,0,0);
        jPanel4.setBackground(clr);
    }//GEN-LAST:event_btn_HomeMouseEntered

    private void btn_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseExited
        Color clr = new Color(0,51,51);
        jPanel4.setBackground(clr);
    }//GEN-LAST:event_btn_HomeMouseExited

    private void btn_SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchMouseEntered
        Color clr = new Color(0,0,0);
        jPanel5.setBackground(clr);
    }//GEN-LAST:event_btn_SearchMouseEntered

    private void btn_SearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchMouseExited
        Color clr = new Color(0,51,51);
        jPanel5.setBackground(clr);
    }//GEN-LAST:event_btn_SearchMouseExited

    private void btn_EditCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditCourseMouseEntered
        Color clr = new Color(0,0,0);
        jPanel6.setBackground(clr);
    }//GEN-LAST:event_btn_EditCourseMouseEntered

    private void btn_EditCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditCourseMouseExited
        Color clr = new Color(0,51,51);
        jPanel6.setBackground(clr);
    }//GEN-LAST:event_btn_EditCourseMouseExited

    private void btn_CourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CourseListMouseEntered
       Color clr = new Color(0,0,0);
        jPanel7.setBackground(clr);
    }//GEN-LAST:event_btn_CourseListMouseEntered

    private void btn_CourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CourseListMouseExited
        Color clr = new Color(0,51,51);
        jPanel7.setBackground(clr);
    }//GEN-LAST:event_btn_CourseListMouseExited

    private void btn_ViewAllRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewAllRecordMouseEntered
        Color clr = new Color(0,0,0);
        jPanel8.setBackground(clr);
    }//GEN-LAST:event_btn_ViewAllRecordMouseEntered

    private void btn_ViewAllRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewAllRecordMouseExited
        Color clr = new Color(0,51,51);
        jPanel8.setBackground(clr);
    }//GEN-LAST:event_btn_ViewAllRecordMouseExited

    private void btn_BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseEntered
       Color clr = new Color(0,0,0);
        jPanel9.setBackground(clr);
    }//GEN-LAST:event_btn_BackMouseEntered

    private void btn_BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseExited
        Color clr = new Color(0,51,51);
        jPanel9.setBackground(clr);
    }//GEN-LAST:event_btn_BackMouseExited

    private void btn_LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseEntered
        Color clr = new Color(0,0,0);
        jPanel3.setBackground(clr);
    }//GEN-LAST:event_btn_LogoutMouseEntered

    private void btn_LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseExited
       Color clr = new Color(0,51,51);
        jPanel3.setBackground(clr);
    }//GEN-LAST:event_btn_LogoutMouseExited

    private void btn_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseClicked
       Login_Page s=new Login_Page();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_LogoutMouseClicked

    private void btn_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseClicked
        Home_Page s = new Home_Page();
        s.show();
        this.dispose();
    }//GEN-LAST:event_btn_HomeMouseClicked

    private void btn_EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseClicked
        UpdateFeeDetails d = new UpdateFeeDetails();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_EditMouseClicked

    private void btn_EditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseEntered
        Color clr = new Color(0,0,0);
        jPanel11.setBackground(clr);
    }//GEN-LAST:event_btn_EditMouseEntered

    private void btn_EditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseExited
        Color clr = new Color(0,51,51);
        jPanel11.setBackground(clr);
    }//GEN-LAST:event_btn_EditMouseExited

    private void btn_Logout2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Logout2MouseClicked
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");

        job.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                pf.setOrientation(PageFormat.LANDSCAPE);
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47, 0.47);

                jPanel2.print(g2);

                return Printable.PAGE_EXISTS;

            }
        });
        boolean ok = job.printDialog();
        if (ok) {
            try {

                job.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_Logout2MouseClicked

    private void btn_Logout2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Logout2MouseEntered
        Color clr = new Color(0,0,0);
        jPanel12.setBackground(clr);
    }//GEN-LAST:event_btn_Logout2MouseEntered

    private void btn_Logout2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Logout2MouseExited
        Color clr = new Color(0,51,51);
        jPanel12.setBackground(clr);
    }//GEN-LAST:event_btn_Logout2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btn_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchMouseClicked
        SearchRecord s=new SearchRecord();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_SearchMouseClicked

    private void btn_EditCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditCourseMouseClicked
        EditCourse s=new EditCourse();
        s.setVisible(true);
        this.dispose();    }//GEN-LAST:event_btn_EditCourseMouseClicked

    private void btn_CourseListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CourseListMouseClicked
        ViewCourse s=new ViewCourse();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CourseListMouseClicked

    private void btn_ViewAllRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewAllRecordMouseClicked
        ViewAllRecord s=new ViewAllRecord();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ViewAllRecordMouseClicked

    private void btn_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseClicked
        Add_Fees s=new Add_Fees();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Back;
    private javax.swing.JLabel btn_CourseList;
    private javax.swing.JLabel btn_Edit;
    private javax.swing.JLabel btn_EditCourse;
    private javax.swing.JLabel btn_Home;
    private javax.swing.JLabel btn_Logout;
    private javax.swing.JLabel btn_Logout2;
    private javax.swing.JLabel btn_Search;
    private javax.swing.JLabel btn_ViewAllRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_BankName;
    private javax.swing.JLabel lbl_Cheque;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel txt_Amount;
    private javax.swing.JLabel txt_BankName;
    private javax.swing.JLabel txt_Cheque;
    private javax.swing.JLabel txt_PaymentMode;
    private javax.swing.JLabel txt_ReceivedForm;
    private javax.swing.JLabel txt_RecieptNo;
    private javax.swing.JLabel txt_Remark;
    private javax.swing.JLabel txt_StreamName;
    private javax.swing.JLabel txt_Total;
    private javax.swing.JLabel txt_TotalInWord;
    private javax.swing.JLabel txt_Year1;
    private javax.swing.JLabel txt_Year2;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_gstin;
    private javax.swing.JLabel txt_s;
    private javax.swing.JLabel txt_sgst;
    // End of variables declaration//GEN-END:variables
}
